---
abstract: 'official client for ONYPHE API access'
author:
  - 'ONYPHE <contact_at_onyphe.io>'
build_requires: {}
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Metabrik-Client-Onyphe
provides:
  Metabrik::Api::Onyphe:
    file: lib/Metabrik/Api/Onyphe.pm
  Metabrik::Client::Onyphe:
    file: lib/Metabrik/Client/Onyphe.pm
    version: '2.01'
requires:
  Metabrik: '1.40'
  Metabrik::Repository: '1.40'
  perl: v5.6.1
resources:
  license: http://opensource.org/licenses/BSD-3-Clause
version: '2.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
